### ISSUE TITLE
fulpNGScrape currently is broken

### ISSUE THREAD

**Issue by ninjamuffin99** [ninjamuffin99/FulpTronJS#2]
```
2018-09-26T21:28:58.294289+00:00 app[worker.1]: RangeError: RichEmbed field values may not exceed 1024 characters.
2018-09-26T21:28:58.294303+00:00 app[worker.1]:     at RichEmbed.addField (/app/node_modules/discord.js/src/structures/RichEmbed.js:157:36)
2018-09-26T21:28:58.294305+00:00 app[worker.1]:     at rp.then (/app/index.js:632:11)
2018-09-26T21:28:58.294308+00:00 app[worker.1]:     at tryCatcher (/app/node_modules/request-promise/node_modules/bluebird/js/release/util.js:16:23)
2018-09-26T21:28:58.294310+00:00 app[worker.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:512:31)
2018-09-26T21:28:58.294311+00:00 app[worker.1]:     at Promise._settlePromise (/app/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:569:18)
2018-09-26T21:28:58.294313+00:00 app[worker.1]:     at Promise._settlePromise0 (/app/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:614:10)
2018-09-26T21:28:58.294315+00:00 app[worker.1]:     at Promise._settlePromises (/app/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:693:18)
2018-09-26T21:28:58.294316+00:00 app[worker.1]:     at Async._drainQueue (/app/node_modules/request-promise/node_modules/bluebird/js/release/async.js:133:16)
2018-09-26T21:28:58.294318+00:00 app[worker.1]:     at Async._drainQueues (/app/node_modules/request-promise/node_modules/bluebird/js/release/async.js:143:10)
2018-09-26T21:28:58.294320+00:00 app[worker.1]:     at Immediate.Async.drainQueues (/app/node_modules/request-promise/node_modules/bluebird/js/release/async.js:17:14)
2018-09-26T21:28:58.294321+00:00 app[worker.1]:     at runCallback (timers.js:810:20)
2018-09-26T21:28:58.294323+00:00 app[worker.1]:     at tryOnImmediate (timers.js:768:5)
2018-09-26T21:28:58.294325+00:00 app[worker.1]:     at processImmediate [as _immediateCallback] (timers.js:745:5)
```

might've been something in the recent Newgrounds updates, or Discord changed RichEmbed shit

**Comment by ninjamuffin99** [comment]
![image](https://user-images.githubusercontent.com/22229331/46110793-9fcd7780-c199-11e8-84aa-ebf552d015c0.png)

seems to semi-work, but on certain profiles its busted, I think if they have a bunch of different submission types (movies, games, audio, art) it fills up the data and runs over the Rich Embed limit

**Comment by ninjamuffin99** [comment]
fixed
